name: Feature Request
description: Suggest an idea to improve the project
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - rxtech-lab

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of what you want to happen
      placeholder: Describe the feature you'd like to see implemented
    validations:
      required: true

  - type: textarea
    id: improvement
    attributes:
      label: How to Improve the Repository
      description: Explain how this feature would improve the repository
      placeholder: |
        - What problem does this solve?
        - How would this benefit users?
        - What value does this add?
    validations:
      required: true

  - type: dropdown
    id: improvement_type
    attributes:
      label: Type of Improvement
      description: What type of improvement does this feature represent?
      options:
        - performance
        - models
        - UI/UX
        - authentication
        - payment
        - usage
        - other
    validations:
      required: true

  - type: textarea
    id: video
    attributes:
      label: Video/Mockup (Optional)
      description: If you have a video demonstration or mockup, please provide it in markdown format
      placeholder: |
        <!-- Upload your video/mockup and link it here -->
        ![Feature demonstration video](video-url-here)
        
        Or provide a link:
        [Video/Mockup link](https://example.com/demo)
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: What other approaches have you thought about?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
